# Generated by Django 5.2 on 2025-08-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
